### ISSUE TITLE
Under heavy logging, an application can become unresponsive

### ISSUE THREAD

**Issue by aweiker** [svetob/logstash-json#18] opened 2017-07-13 17:29 UTC
I came across this issue when I was using this in production. We had an increase in traffic and because of some detailed logging the application became unresponsive as logging appeared to be blocking on this line: https://github.com/svetob/logstash-json/blob/master/lib/logstash_json_tcp.ex#L49

When I looked in observer there were several hundred thousand messages waiting on this line of code.

**Comment by svetob** [comment] 2017-07-17 15:06
I see. What's happening is that the message buffer before logstash sending is being filled up, causing logging to block until logs have been sent to logstash and space is available in the buffer.

This is probably a symptom of logs being produced faster than logstash can consume them, but just to make sure it's not a problem with the library: do you have any numbers on the max throughput in logs/second your logstash backend can handle, versus how much your applications were producing per second during the spike?

Assuming that the problem is a momentary spike exceeding what the backend can consume, there is not much we can do about it in the library.

We could drop log messages instead of block, but I would prefer the library to never drop messages if possible.

Another option is to have no limit on queue size, however you are then running into potential OOM-problems instead. You can try increasing the `buffer_size` config to something much higher to trade memory for spike tolerance.

**Comment by svetob** [comment] 2017-10-11 08:38
Closing this for now. If you again encounter issues with the lib underperforming compared to volumes you know your logging backend can handle, feel free to reopen this.

**Closed as completed by svetob** 2017-10-11 08:38 UTC
